<a href="https://colab.research.google.com/github/yohanesnuwara/reservoir-engineering/blob/master/Reservoir%20Simulation%20Ertekin/Unit%205%20Finite-Difference%20Approximation%20to%20Linear-Flow%20Equations/fd_linearflow_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Unit 5 Exercises**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [16]:
!git clone https://github.com/yohanesnuwara/reservoir-engineering

Cloning into 'reservoir-engineering'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 941 (delta 15), reused 0 (delta 0), pack-reused 909
Receiving objects: 100% (941/941), 12.23 MiB | 39.52 MiB/s, done.
Resolving deltas: 100% (410/410), done.

## Exercise 5.5

<div>
<img src="https://user-images.githubusercontent.com/51282928/76333376-22151180-6324-11ea-82bc-b659ef6374b2.PNG" width="500"/>
</div>

### Explicit, timestep 10 days

In [10]:
"Task. determine pressure distribution during first year of production with timestep 10 days"

# known
p_initial = 4500 # initial pressure, in psia
delta_x = 1000 # ft
delta_y = 750
delta_z = 50
ngrid = 6
B = 1 # phase FVF, assumed constant over pressure, rb/stb
c = 1.6E-06 # phase compressibility, psi^-1
k_x = 50 # perm in x direction, md
poro = 0.27
mu = 30 # phase viscosity, cp

delta_t = 10 # days

# conversion
k_x = k_x * 1E-03 # darcy to mD

# calculate factor
Vb = delta_x * delta_y * delta_z
alpha = 5.615 # volume conversion factor, is a constant
factor = (alpha * B * delta_t) / (Vb * poro * c)
factor

3.46604938271605

In [11]:
# calculate transmissibility of coupling cells
beta = 1.127 # transmissibility conversion factor, is a constant
Ax = delta_y * delta_z
T_plus_half = beta * ((Ax * k_x) / (mu * B * delta_x))
T_min_half = T_plus_half
T_min_half, T_plus_half

(0.0704375, 0.0704375)

In [12]:
q = np.full(ngrid-1, T_min_half)
Ti_plus_halves = np.append(q, [0])
print(Ti_plus_halves)
p = np.full(ngrid-1, T_plus_half)
Ti_min_halves = np.append([0], p)
print(Ti_min_halves)
print("At grid 1, the coupling transmissibility coeffs are:", Ti_min_halves[0], "for T_min_half and:", Ti_plus_halves[0], "for T_plus_half.")
print("At grid 3, the coupling transmissibility coeffs are:", Ti_min_halves[2], "for T_min_half and:", Ti_plus_halves[2], "for T_plus_half.")
print("At grid 5, the coupling transmissibility coeffs are:", Ti_min_halves[4], "for T_min_half and:", Ti_plus_halves[4], "for T_plus_half.")

[0.0704375 0.0704375 0.0704375 0.0704375 0.0704375 0.       ]
[0.        0.0704375 0.0704375 0.0704375 0.0704375 0.0704375]
At grid 1, the coupling transmissibility coeffs are: 0.0 for T_min_half and: 0.0704375 for T_plus_half.
At grid 3, the coupling transmissibility coeffs are: 0.0704375 for T_min_half and: 0.0704375 for T_plus_half.
At grid 5, the coupling transmissibility coeffs are: 0.0704375 for T_min_half and: 0.0704375 for T_plus_half.

In [0]:
qsc = [40, -150, 0, 0, 100, 0] # production well in grid 4

In [14]:
pi = np.full(ngrid, p_initial) # array of pressure in each grid [6000, 6000, 6000, 6000, 6000]
time = np.arange(15, 370, delta_t)

pi_arr = []
min_arr = []
plus_arr = []

for j in range(len(time)):
  pnew_arr = []

  minus = pi[0]
  plus = pi[-1]
  minus_arr = []
  plusus_arr = []
  for i, obj in enumerate(pi):
    if i > 0:
      minus = pi[i-1]
    if i < (len(pi) - 1):
      plus = pi[i+1]

    pnew = pi[i] + (factor * ((Ti_plus_halves[i] * plus) - ((Ti_plus_halves[i] + Ti_min_halves[i]) * pi[i]) + (Ti_min_halves[i] * minus))) + (factor * qsc[i])
    pnew_arr.append(float(pnew))

    minus_arr.append(float(minus))
    plusus_arr.append(float(plus))

  pi = pnew_arr

  min_arr.append(minus_arr)
  plus_arr.append(plusus_arr)
  pi_arr.append(pi)

df = pd.DataFrame.from_records(pi_arr)
df = pd.DataFrame(pd.np.column_stack([time, df]), columns=['time', 'grid 1', 'grid 2', 'grid 3', 'grid 4', 'grid 5', 'grid6'])
df

     time       grid 1       grid 2  ...       grid 4       grid 5        grid6
0    15.0  4638.641975  3980.092593  ...  4500.000000  4846.604938  4500.000000
1    25.0  4616.505801  3747.893453  ...  4584.620079  5023.969719  4584.620079
2    35.0  4543.084885  3592.679419  ...  4640.235001  5156.049144  4691.882836
3    45.0  4449.695009  3470.674387  ...  4676.286249  5263.401798  4805.204330
4    55.0  4349.319033  3366.889318  ...  4702.391037  5354.804170  4917.068593
5    65.0  4248.110762  3274.657751  ...  4723.447483  5435.260362  5023.937292
6    75.0  4149.094062  3190.642190  ...  4741.755234  5507.663054  5124.357646
7    85.0  4053.739738  3113.036617  ...  4758.360880  5573.699243  5217.937772
8    95.0  3962.718591  3040.786072  ...  4773.721984  5634.392040  5304.793326
9   105.0  3876.280096  2973.218541  ...  4788.026532  5690.404935  5385.261508
10  115.0  3794.448756  2909.864003  ...  4801.345660  5742.205671  5459.759179
11  125.0  3717.128339  2850.363355  ...  4813.705399  5790.152739  5528.715624
12  135.0  3644.158438  2794.421827  ...  4825.119073  5834.540748  5592.542843
13  145.0  3575.345842  2741.784777  ...  4835.600791  5875.624294  5651.624176
14  155.0  3510.482341  2692.224881  ...  4845.170077  5913.630691  5706.311532
15  165.0  3449.355060  2645.535131  ...  4853.852571  5948.766942  5756.926401
16  175.0  3391.752556  2601.524850  ...  4861.679156  5981.223725  5803.762323
17  185.0  3337.468455  2560.017262  ...  4868.684605  6011.177815  5847.087723
18  195.0  3286.303610  2520.847881  ...  4874.906230  6038.793698  5887.148654
19  205.0  3238.067336  2483.863360  ...  4880.382722  6064.224722  5924.171253
20  215.0  3192.578063  2448.920569  ...  4885.153217  6087.614014  5958.363886
21  225.0  3149.663607  2415.885843  ...  4889.256588  6109.095242  5989.918994
22  235.0  3109.161186  2384.634309  ...  4892.730925  6128.793279  6019.014666
23  245.0  3070.917276  2355.049289  ...  4895.613168  6146.824800  6045.816000
24  255.0  3034.787346  2327.021751  ...  4897.938864  6163.298841  6070.476274
25  265.0  3000.635533  2300.449802  ...  4899.742006  6178.317292  6093.137962
26  275.0  2968.334266  2275.238218  ...  4901.054953  6191.975378  6113.933631
27  285.0  2937.763874  2251.298006  ...  4901.908391  6204.362092  6132.986731
28  295.0  2908.812173  2228.545995  ...  4902.331336  6215.560605  6150.412302
29  305.0  2881.374063  2206.904457  ...  4902.351161  6225.648645  6166.317599
30  315.0  2855.351128  2186.300747  ...  4901.993638  6234.698856  6180.802672
31  325.0  2830.651241  2166.666974  ...  4901.283003  6242.779131  6193.960878
32  335.0  2807.188195  2147.939687  ...  4900.242014  6249.952920  6205.879359
33  345.0  2784.881336  2130.059587  ...  4898.892023  6256.279523  6216.639472
34  355.0  2763.655226  2112.971252  ...  4897.253050  6261.814360  6226.317188
35  365.0  2743.439311  2096.622888  ...  4895.343852  6266.609226  6234.983463

[36 rows x 7 columns]

### Implicit, timestep 10 days

In [15]:
# known
p_initial = 4500 # initial pressure, in psia
delta_x = 1000 # ft
delta_y = 750
delta_z = 50
ngrid = 6
B = 1 # phase FVF, assumed constant over pressure, rb/stb
c = 1.6E-06 # phase compressibility, psi^-1
k_x = 50 # perm in x direction, md
poro = 0.27
mu = 30 # phase viscosity, cp

delta_t = 10 # days

# conversion
k_x = k_x * 1E-03 # darcy to mD

# calculate factor
Vb = delta_x * delta_y * delta_z
alpha = 5.615 # volume conversion factor, is a constant
factor = (Vb * poro * c) / (alpha * B * delta_t)
factor

0.2885129118432769

In [17]:
import sys, os
sys.path.append('/content/reservoir-engineering/Reservoir Simulation Ertekin/Unit 5 Finite-Difference Approximation to Linear-Flow Equations')
from tdma_implicit import TDMAsolver

pi = np.full(ngrid, p_initial) # array of pressure in each grid [6000, 6000, 6000, 6000, 6000]
time = np.arange(15, 370, delta_t)

p_new_arr = []

for j in range(len(time)):
  pi_next_plus_arr = []
  pi_next_arr = []
  pi_next_minus_arr = []
  pi_arr = []

  for i in range(len(pi)):
    pi_next_plus = Ti_plus_halves[i]
    pi_next = -(factor + Ti_plus_halves[i] + Ti_min_halves[i])
    pi_next_minus = Ti_min_halves[i]
    pi_current = -(qsc[i] + (factor * pi[i]))

    pi_next_plus_arr.append(float(pi_next_plus))
    pi_next_arr.append(float(pi_next))
    pi_next_minus_arr.append(float(pi_next_minus))
    pi_arr.append(float(pi_current))

  pi_next_plus_arr = pi_next_plus_arr[:-1]
  pi_next_minus_arr = pi_next_minus_arr[1:]

  p_new = TDMAsolver(pi_next_minus_arr, pi_next_arr, pi_next_plus_arr, pi_arr)
  p_new_arr.append(p_new)
  pi = p_new # updating pi

df = pd.DataFrame.from_records(p_new_arr)
df = pd.DataFrame(pd.np.column_stack([time, df]), columns=['time', 'grid 1', 'grid 2', 'grid 3', 'grid 4', 'grid 5', 'grid 6'])
df

     time       grid 1       grid 2  ...       grid 4       grid 5       grid 6
0    15.0  4542.570415  4149.060061  ...  4531.768822  4746.020507  4548.277057
1    25.0  4527.801179  3899.426871  ...  4571.921040  4930.206825  4623.223838
2    35.0  4479.162652  3712.059290  ...  4610.981564  5074.912177  4711.859472
3    45.0  4411.036500  3564.111571  ...  4645.778865  5193.349588  4806.343164
4    55.0  4332.317423  3442.003742  ...  4675.808872  5293.538755  4901.946451
5    65.0  4248.542635  3337.520690  ...  4701.555174  5380.485254  4995.851001
6    75.0  4163.168119  3245.593673  ...  4723.754485  5457.405189  5086.422629
7    85.0  4078.344121  3163.024600  ...  4743.105961  5526.427261  5172.765548
8    95.0  3995.392781  3087.743693  ...  4760.179834  5589.003966  5254.444779
9   105.0  3915.106223  3018.372118  ...  4775.408931  5646.157825  5331.311351
10  115.0  3837.934926  2953.960968  ...  4789.109654  5698.632072  5403.391372
11  125.0  3764.108158  2893.833434  ...  4801.509318  5746.984796  5470.815342
12  135.0  3693.711807  2837.488118  ...  4812.770939  5791.648867  5533.773095
13  145.0  3626.739161  2784.539011  ...  4823.012873  5832.970737  5592.485199
14  155.0  3563.124315  2734.677756  ...  4832.323304  5871.235930  5647.184968
15  165.0  3502.764305  2687.649595  ...  4840.770434  5906.686023  5698.107338
16  175.0  3445.533851  2643.237846  ...  4848.409433  5939.530092  5745.482169
17  185.0  3391.295214  2601.253728  ...  4855.287024  5969.952527  5789.530401
18  195.0  3339.904785  2561.529599  ...  4861.444446  5998.118431  5830.462014
19  205.0  3291.217493  2523.914388  ...  4866.919318  6024.177417  5868.475144
20  215.0  3245.089719  2488.270434  ...  4871.746765  6048.266299  5903.755893
21  225.0  3201.381209  2454.471262  ...  4875.960089  6070.511064  5936.478567
22  235.0  3159.956295  2422.399982  ...  4879.591135  6091.028322  5966.806150
23  245.0  3120.684635  2391.948081  ...  4882.670487  6109.926422  5994.890904
24  255.0  3083.441638  2363.014515  ...  4885.227559  6127.306315  6020.875024
25  265.0  3048.108656  2335.504978  ...  4887.290627  6143.262253  6044.891295
26  275.0  3014.573023  2309.331311  ...  4888.886835  6157.882364  6067.063741
27  285.0  2982.727992  2284.411008  ...  4890.042193  6171.249135  6087.508232
28  295.0  2952.472598  2260.666788  ...  4890.781572  6183.439838  6106.333068
29  305.0  2923.711476  2238.026221  ...  4891.128706  6194.526896  6123.639505
30  315.0  2896.354647  2216.421397  ...  4891.106197  6204.578216  6139.522257
31  325.0  2870.317292  2195.788623  ...  4890.735530  6213.657488  6154.069950
32  335.0  2845.519510  2176.068149  ...  4890.037097  6221.824462  6167.365543
33  345.0  2821.886079  2157.203916  ...  4889.030223  6229.135196  6179.486716
34  355.0  2799.346216  2139.143320  ...  4887.733196  6235.642293  6190.506228
35  365.0  2777.833341  2121.836999  ...  4886.163307  6241.395116  6200.492248

[36 rows x 7 columns]

## Exercise 5.7

<div>
<img src="https://user-images.githubusercontent.com/51282928/76335943-da908480-6327-11ea-898b-4686f2d79e14.PNG" width="500"/>
</div>

## Example 5.12 Rework Exercise 5.8 With Varying Phase FVF 

![Example 5 8](https://user-images.githubusercontent.com/51282928/75949840-09e36380-5eda-11ea-824c-dd5c9ac6f6d5.PNG)

In [0]:
# known
p_initial = 6000 # initial pressure, in psia
delta_x = 1000 # ft
delta_y = 1000
delta_z = 75
ngrid = 5
grid_loc = 4 # grid location where production well is located
B = 1 # phase FVF, assumed constant over pressure, rb/stb
c = 3.5E-06 # phase compressibility, psi^-1
k_x = 15 # perm in x direction, md
poro = 0.18
mu = 10 # phase viscosity, cp

delta_t = 10 # days
qsc = -150 # minus means production, stb/d

# conversion
k_x = k_x * 1E-03 # darcy to mD

# calculate factor
Vb = delta_x * delta_y * delta_z
alpha = 5.615 # volume conversion factor, is a constant
factor = (alpha * B * delta_t) / (Vb * poro * c)
factor